# Generated by Django 6.0.3 on 2026-03-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_app', '0002_remove_todolist_end_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
